### SIGNUP
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "João Pedro Soares",
    "email": "jp.soares@gmail.com",
    "password": "12345678",
    "role": "ADMIN"
}


### LOGIN
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "fran_hahn@hotmail.com",
    "password": "12345678"
}


### CREATE BAND
POST http://localhost:3003/bands/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgyZDE2MmM5LTcwZjMtNDY0Ny05MDQ0LWI2NTc5NzRlODMzOSIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3ODU3MjM0MywiZXhwIjoxNjc4NTc1OTQzfQ.JVUW-f-3n9SMnuf8NserIB0CB1Ngn8qSN_LOZtj7w7o
Content-Type: application/json

{
    "name": "Jota Quest",
    "musicGenre": "Pop Rock",
    "responsible": "Rogério Flausino"
}